default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  <<: *default
  channel_prefix: campfire_development

test:
  adapter: test

performance:
  <<: *default
  channel_prefix: campfire_performance

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  channel_prefix: campfire_production
